<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211151300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_like BOOLEAN NOT NULL, comment_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A55E25FF8697D13 ON comment_like (comment_id)');
        $this->addSql('CREATE INDEX IDX_8A55E25F7E3C61F9 ON comment_like (owner_id)');
        $this->addSql('ALTER TABLE comment_like ADD CONSTRAINT FK_8A55E25FF8697D13 FOREIGN KEY (comment_id) REFERENCES comment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment_like ADD CONSTRAINT FK_8A55E25F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video DROP likes');
        $this->addSql('ALTER TABLE video DROP dislikes');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment_like DROP CONSTRAINT FK_8A55E25FF8697D13');
        $this->addSql('ALTER TABLE comment_like DROP CONSTRAINT FK_8A55E25F7E3C61F9');
        $this->addSql('DROP TABLE comment_like');
        $this->addSql('ALTER TABLE video ADD likes INT NOT NULL');
        $this->addSql('ALTER TABLE video ADD dislikes INT NOT NULL');
    }
}
