<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211123541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE video_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_like BOOLEAN NOT NULL, video_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ABF41D6F29C1004E ON video_like (video_id)');
        $this->addSql('CREATE INDEX IDX_ABF41D6F7E3C61F9 ON video_like (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_video_user ON video_like (video_id, owner_id)');
        $this->addSql('ALTER TABLE video_like ADD CONSTRAINT FK_ABF41D6F29C1004E FOREIGN KEY (video_id) REFERENCES video (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video_like ADD CONSTRAINT FK_ABF41D6F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE video_like DROP CONSTRAINT FK_ABF41D6F29C1004E');
        $this->addSql('ALTER TABLE video_like DROP CONSTRAINT FK_ABF41D6F7E3C61F9');
        $this->addSql('DROP TABLE video_like');
    }
}
